//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnxForm.src.SmartQuant.FinChart {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChartToolBar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ChartToolBar() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnxForm.src.SmartQuant.FinChart.ChartToolBar", typeof(ChartToolBar).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes imageList_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("imageList.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.Windows.Forms.ImageListStreamer.
        /// </summary>
        internal static System.Windows.Forms.ImageListStreamer imageList_ImageStream {
            get {
                object obj = ResourceManager.GetObject("imageList.ImageStream", resourceCulture);
                return ((System.Windows.Forms.ImageListStreamer)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.Drawing.Point similar to {X=205,Y=17}.
        /// </summary>
        internal static System.Drawing.Point imageList_Location {
            get {
                object obj = ResourceManager.GetObject("imageList.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes imageList_Modifiers {
            get {
                object obj = ResourceManager.GetObject("imageList.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolTip_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("toolTip.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        internal static System.Drawing.Point toolTip_Location {
            get {
                object obj = ResourceManager.GetObject("toolTip.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolTip_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolTip.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
    }
}
