//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnxForm.src.SmartQuant.FinChart {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolBar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ToolBar() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnxForm.src.SmartQuant.FinChart.ToolBar", typeof(ToolBar).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnBar_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("btnBar.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnBar_Modifiers {
            get {
                object obj = ResourceManager.GetObject("btnBar.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnCandle_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("btnCandle.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnCandle_Modifiers {
            get {
                object obj = ResourceManager.GetObject("btnCandle.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnCrosshair_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("btnCrosshair.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnCrosshair_Modifiers {
            get {
                object obj = ResourceManager.GetObject("btnCrosshair.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnCursor_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("btnCursor.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnCursor_Modifiers {
            get {
                object obj = ResourceManager.GetObject("btnCursor.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnFixed_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("btnFixed.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnFixed_Modifiers {
            get {
                object obj = ResourceManager.GetObject("btnFixed.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnLine_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("btnLine.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnLine_Modifiers {
            get {
                object obj = ResourceManager.GetObject("btnLine.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnLinear_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("btnLinear.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnLinear_Modifiers {
            get {
                object obj = ResourceManager.GetObject("btnLinear.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnLog_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("btnLog.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnLog_Modifiers {
            get {
                object obj = ResourceManager.GetObject("btnLog.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnPnF_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("btnPnF.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnPnF_Modifiers {
            get {
                object obj = ResourceManager.GetObject("btnPnF.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnTrailing_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("btnTrailing.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnTrailing_Modifiers {
            get {
                object obj = ResourceManager.GetObject("btnTrailing.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnWholeRange_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("btnWholeRange.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnWholeRange_Modifiers {
            get {
                object obj = ResourceManager.GetObject("btnWholeRange.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnZoomIn_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("btnZoomIn.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnZoomIn_Modifiers {
            get {
                object obj = ResourceManager.GetObject("btnZoomIn.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnZoomOut_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("btnZoomOut.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes btnZoomOut_Modifiers {
            get {
                object obj = ResourceManager.GetObject("btnZoomOut.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes chartToolBar_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("chartToolBar.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool chartToolBar_Locked {
            get {
                object obj = ResourceManager.GetObject("chartToolBar.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes chartToolBar_Modifiers {
            get {
                object obj = ResourceManager.GetObject("chartToolBar.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes imageList_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("imageList.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.Windows.Forms.ImageListStreamer.
        /// </summary>
        internal static System.Windows.Forms.ImageListStreamer imageList_ImageStream {
            get {
                object obj = ResourceManager.GetObject("imageList.ImageStream", resourceCulture);
                return ((System.Windows.Forms.ImageListStreamer)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        internal static System.Drawing.Point imageList_Location {
            get {
                object obj = ResourceManager.GetObject("imageList.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes imageList_Modifiers {
            get {
                object obj = ResourceManager.GetObject("imageList.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolBarButton2_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButton2.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolBarButton2_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButton2.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolBarButton3_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButton3.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolBarButton3_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButton3.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolBarButton6_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButton6.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolBarButton6_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButton6.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolBarButton9_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButton9.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolBarButton9_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButton9.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolTip_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("toolTip.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.Drawing.Point similar to {X=116,Y=17}.
        /// </summary>
        internal static System.Drawing.Point toolTip_Location {
            get {
                object obj = ResourceManager.GetObject("toolTip.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///    Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolTip_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolTip.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
    }
}
